-- 코드를 입력하세요
WITH RENT AS(
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, H.HISTORY_ID,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS PERIOD,
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE 'NONE' END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭')
    
SELECT R.HISTORY_ID,
    ROUND(DAILY_FEE * PERIOD * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P RIGHT JOIN RENT R
    ON P.DURATION_TYPE = R.DURATION_TYPE AND P.CAR_TYPE = R.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
 